name: project
description: "Frontend dev"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  form_validator: ^2.1.1
  flutter_animate: ^4.1.1+1
  fl_chart: ^0.55.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Ledger
      fonts:
        - asset: assets/fonts/Ledger-Regular.ttf
    - family: Crimson Text
      fonts:
        - asset: assets/fonts/CrimsonText-Regular.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

  assets:
    - assets/images/
    - assets/fonts/